spring:
  datasource:
    url: jdbc:postgresql://mydbinstance.cbwcasc2onzg.eu-central-1.rds.amazonaws.com:5432/postgres
    username: jiraClone
    password: jiraClone123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml  # Path to the changelog file
    default-schema: public  # Optional: Set the default schema for the changes
    drop-first: false  # Optional: Whether to drop the schema before updating
